version: "3.9"

services:
  api:
    build: ./server
    container_name: bombio-api
    environment:
      NODE_ENV: production
    expose:
      - "3001"
    # wenn du Logs etc willst, kannst du spaeter Volumes hinzufuegen

  client:
    build: ./client
    container_name: bombio-client
    expose:
      - "80"

  caddy:
    image: caddy:2-alpine
    container_name: bombio-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - client

volumes:
  caddy_data:
  caddy_config:
